### PR TITLE
Fix typo for empty quantities

### LINKED ISSUE #39: Negative value don't include zero
In QuantityChecker class if a value is not greater than zero, an exception is thrown. It should be thrown only when the number is not greater or equal than zero.

### PR DESCRIPTION
**Pull request by GiackAloZ**
fixed #39

### CODE REVIEW

File: src/main/java/nwoolcan/model/utils/QuantityChecker.java [hunk 1]
```diff
@@ -23,14 +23,14 @@ private QuantityChecker() { }
 
     /**
      * Performs a check on the {@link Quantity} passed by parameter, returning a {@link Result}
-     * with a {@link IllegalArgumentException} error if the quantity value is null or the quantity
```
Comment (Zeegomo) [inline src/main/java/nwoolcan/model/utils/QuantityChecker.java]: I think you should check also that the value is not null, is will be as easy as using `Results.requireNonNull(quantity)` instead of `Result.of(quantity)`
